Pass message to error handler
nowait/amqp pull request #10
Opened 2017-03-23 21:14 UTC by briancavalier

The main purpose of this PR is to pass both the Error and AMQP Message to error handlers when using defaultParseAndHandleMessage.

### Motivation

This helps in logging more useful information about failed messages, since many times, the Error object contains only a generic description and stack trace.  For example, in many of our use cases, it would be useful to be able to log additional info, like the associated businessId or visitId, which probably only exists in the message payload.

### Other changes

This PR also:

* Updates all deps and devDeps, including refactoring to appease newer jsinspect strictness
* Switches from isparta to [nyc](https://github.com/istanbuljs/nyc).  [Isparta is no longer maintained](https://github.com/douglasduteil/isparta#isparta---), and nyc is the new official front end to istanbul code coverage.  The [license is ISC](https://github.com/istanbuljs/nyc/blob/master/LICENSE.txt), which is functionally equivalent to MIT.
* Tightens types on a few things, including error handlers.

2017-03-23 21:18 UTC, briancavalier commented
This PR should also help with #9, since it updates to a much newer version of eslint.

2017-03-23 22:29 UTC, ddelnano commented on .gitignore
> +.DS_Store
@briancavalier should we make this recursive just cause?

2017-03-23 22:33 UTC, briancavalier commented on .gitignore
> +.DS_Store
Sure

2017-03-24 00:56 UTC, briancavalier commented on .gitignore
> +.DS_Store
Done in f94fb93

2017-03-24 02:15 UTC, raychan requested changes
Few minor comments

2017-03-24 02:15 UTC, raychan commented on test/defaultParseAndHandleMessage-test.js
>        throw new Error()
```
const error = new Error();
const handleError = async (err) => {
      assert.strictEqual(error, err)
}

const handleMessage = async (data) => {
      assert.equal(content, JSON.stringify(data))
      throw error
}
```

2017-03-24 10:44 UTC, ddelnano commented
Took me a while to wrap my head around this since I haven't look at this functional JS in a while but aside from @raychan's comment (which I didn't think about when I got my head wrapped around things) lgtm

2017-03-24 10:45 UTC, ddelnano commented
And ❤️ that this should fix #9.  After we merge this @briancavalier can you rebase #9 and see if that fixes things?

2017-03-24 20:46 UTC, briancavalier commented on test/defaultParseAndHandleMessage-test.js
> +    assert.equal(expectedAckCount, ackCount)
:+1:

2017-03-24 20:50 UTC, briancavalier commented on test/defaultParseAndHandleMessage-test.js
>      const handleError = async (error) => {
I think it's sufficient to assert [here](https://github.com/nowait/amqp/blob/d72ef659b56b7db24c6ef886258287b835cac0f2/test/defaultParseAndHandleMessage-test.js#L30).

2017-03-24 20:52 UTC, briancavalier commented on test/defaultParseAndHandleMessage-test.js
>        throw new Error()
Good call.

2017-03-24 20:58 UTC, briancavalier commented
FWIW, this is an API-breaking change (existing `handleError` functions passed to `defaultParseAndHandleMessage` won't type check), so it'll require a major version bump when we release it.

2017-03-24 20:58 UTC, briancavalier commented
@ray Addressed your feedback in 4d27dc7

2017-03-28 00:43 UTC, raychan approved these changes

2017-03-28 00:43 UTC, raychan commented
LGTM

2017-03-29 15:11 UTC, briancavalier commented
I'll merge this and publish a major version bump.

2017-03-29 15:11 UTC, merged